import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next JS - About",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <p>Layout About</p>
      {children}
    </div>
  );
}
